apiVersion: apps/v1
kind: Deployment
metadata:
  name: bggapp-deploy
  namespace: bggns
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bggapp
  template:
    metadata:
      labels:
        app: bggapp
    spec:
      containers:
      - name: bgg-backend
        image: stackupiss/bgg-backend:v1
        env:
        - name: BGG_DB_HOST
          valueFrom:
            configMapKeyRef:
              name: bgg-cm
              key: BGG_DB_HOST
        - name: BGG_DB_USER
          valueFrom:
            secretKeyRef:
              name: bgg-secret
              key: BGG_DB_USER
        - name: BGG_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: bgg-secret
              key: BGG_DB_PASSWORD
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: bggapp-service
  namespace: bggns
spec:
  selector:
    app: bggapp
  ports:
    - name: web
      protocol: TCP
      port: 80
      targetPort: 3000
      # nodePort: 30000
  # type: LoadBalancer
  type: ClusterIP
